batch_size: 64
test_batch_size: 1
epochs: 50
optimizer: 'adam'
path_to_ckpt: 'codi/checkpoint/weights.tf'
loss: 'binary_crossentropy'
patience: 5
path_to_scaler: 'codi/scaler.pkl'
features: ['logit', 'margin', 'ratio', 'entropy', 'kl_divergence']
filtering: {'exp': False, 'thresh' : [1.0], 'nb_thresh' : 20, 'by_percentage' : True, 'in_between' : False}
feature_dict: {'logits': [0, 2], 'logit_margin': [2], 
               'logit_ratio': [3], 'entropy':  [4], 'data': [5, 405]}
