batch_size: 64
test_batch_size: 1
epochs: 50
optimizer: 'adam'
path_to_ckpt: 'codi/checkpoint/weights.tf'
loss: 'binary_crossentropy'
patience: 5
path_to_scaler: 'codi/scaler.pkl'
features: ['logits', 'nbests']
filtering: {'exp': '1', 'thresh' : [0.5], 'nb_thresh' : 6, 'by_percentage' : False, 'in_between' : True}
feature_dict: {'logits': [0, 2], 'logit_margin': [2], 
               'logit_ratio': [3], 'entropy':  [4], 'data': [5, 405]}
