available_datasets:
  - 'imdb'
  - 'trec'

max_vocab_size: 25000

portion_used: 1.0

train_split_ratio:
  - 0.008
  - 0.15
  - 0.842

test_split_ratio:
  - 0.1
  - 0.8
  - 0.1

vocab_vector: 'glove.6B.100d'
batch_size: 64
