available_datasets:
  - 'imdb'
  - 'trec'

max_vocab_size: 25000

portion_used: 1.0

train_split_ratio:
  - 0.1
  - 0.2
  - 0.7

test_split_ratio:
  - 0.45
  - 0.1
  - 0.45

vocab_vector: 'glove.6B.100d'
batch_size: 64
